# apt
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/apt.8.gz
complete -c apt -s h -l help -d 'Show a short usage summary'
complete -c apt -s v -l version -d 'Show the program version'
complete -c apt -l audit -d 'Show audit (and notice) messages'
complete -c apt -s c -l config-file -d 'Configuration File; Specify a configuration file to use'
complete -c apt -s o -l option -d 'Set a Configuration Option; This will set an arbitrary configuration option'
complete -c apt -l cli-version -d 'Requests a specific CLI version.  This is a pattern that takes a MAJOR'
complete -c apt -l no-color -l color -d 'Turn colors on or off'
complete -c apt -o f- -l no-f
complete -c apt -s f -d 'or several other variations'

