# ar
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/ar.1.gz
complete -c ar -l format -d 'This option allows for default, gnu, darwin, bsd or coff <type> to be selected'
complete -c ar -s h -l help -d 'Print a summary of command-line options and their meanings'
complete -c ar -s M -d 'This option allows for MRI scripts to be read through the standard input stre…'
complete -c ar -l output -d 'Specify a directory where archive members should be extracted to'
complete -c ar -l thin -d 'When creating or modifying an archive, this option specifies that the archive…'
complete -c ar -l version -d 'Display the version of the llvm-ar executable'
complete -c ar -s X -d 'Specifies the type of object file llvm-ar will recognise'
complete -c ar -l plugin
complete -c ar -l rsp-quoting

