# c++filt
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/c++filt.1.gz
complete -c c++filt -l format -s s -d 'Mangling scheme to assume'
complete -c c++filt -l help -s h -d 'Print a summary of command line options'
complete -c c++filt -l no-params -s p -d 'Do not demangle function parameters or return types'
complete -c c++filt -l no-strip-underscore -s n -d 'Do not strip a leading underscore'
complete -c c++filt -l quote -d 'Add " " around demangled names.  Do not quote already quoted names'
complete -c c++filt -l strip-underscore -s _ -d 'Strip a single leading underscore, if present, from each input name before de…'
complete -c c++filt -l types -s t -d 'Attempt to demangle names as type names as well as symbol names'
complete -c c++filt -l version -d 'Display the version of the llvm-cxxfilt executable'

