# kprop
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/kprop.8.gz
complete -c kprop -s r -d 'Specifies the realm of the primary server'
complete -c kprop -s f -d 'Specifies the filename where the dumped principal database file is to be foun…'
complete -c kprop -s P -d 'Specifies the port to use to contact the \\%kpropd server on the remote host'
complete -c kprop -s d -d 'Prints debugging information'
complete -c kprop -s s -d 'Specifies the location of the keytab file'

