# kswitch
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/kswitch.1.gz
complete -c kswitch -s c -d 'Directly specifies the credential cache to be made primary'
complete -c kswitch -s p -d 'Causes the cache collection to be searched for a cache containing credentials…'

