# size
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/size.1.gz
complete -c size -s A -d 'Equivalent to \\%--format with a value of sysv'
complete -c size -l arch -d 'Architecture(s) from Mach-O universal binaries to display information for'
complete -c size -s B -d 'Equivalent to \\%--format with a value of berkeley'
complete -c size -l common -d 'Include ELF common symbol sizes in bss size for berkeley output format, or as…'
complete -c size -s d -d 'Equivalent to \\%--radix with a value of 10'
complete -c size -s l -d 'Display verbose address and offset information for segments and sections in M…'
complete -c size -l format -d 'Set the output format to the <format> specified'
complete -c size -l help -s h -d 'Display a summary of command line options'
complete -c size -s m -d 'Equivalent to \\%--format with a value of darwin'
complete -c size -s o -d 'Equivalent to \\%--radix with a value of 8'
complete -c size -l radix -d 'Display size information in the specified radix'
complete -c size -l totals -s t -d 'Applies only to berkeley output format'
complete -c size -l version -d 'Display the version of the llvm-size executable'
complete -c size -s x -d 'Equivalent to \\%--radix with a value of 16'

