# ssh-agent
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/ssh-agent.1.gz
complete -c ssh-agent -s a -d 'Bind the agent to the UNIX-domain socket bind_address'
complete -c ssh-agent -s c -d 'Generate C-shell commands on standard output'
complete -c ssh-agent -s D -d 'Foreground mode.  When this option is specified, ssh-agent will not fork'
complete -c ssh-agent -s d -d 'Debug mode'
complete -c ssh-agent -s E -d 'Specifies the hash algorithm used when displaying key fingerprints'
complete -c ssh-agent -s k -d 'Kill the current agent (given by the R SSH_AGENT_PID environment variable)'
complete -c ssh-agent -s O -d 'Specify an option when starting '
complete -c ssh-agent -s P -d 'Specify a pattern-list of acceptable paths for PKCS#11 provider and FIDO auth…'
complete -c ssh-agent -s s -d 'Generate Bourne shell commands on standard output'
complete -c ssh-agent -s T -d 'Bind the agent socket in a randomised subdirectory of the form $TMPDIR/ssh-XX…'
complete -c ssh-agent -s t -d 'Set a default value for the maximum lifetime of identities added to the agent'
complete -c ssh-agent -s U -d 'Instructs ssh-agent not to clean up stale agent sockets under $HOME/'
complete -c ssh-agent -s u -d 'Instructs ssh-agent to only clean up stale agent sockets under $HOME/'
complete -c ssh-agent -s S -d or
complete -c ssh-agent -s A -d 'option to ssh(1) (but see the caveats documented therein), avoiding the need …'
complete -c ssh-agent -o nosplit -d 'OpenSSH is a derivative of the original and free ssh 1. 2. 12 release by'

