# strings
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/strings.1.gz
complete -c strings -l all -s a -d 'Silently ignored.  Present for GNU strings compatibility'
complete -c strings -l bytes -s n -d 'Set the minimum number of printable ASCII characters required for a sequence …'
complete -c strings -l help -s h -d 'Display a summary of command line options'
complete -c strings -l print-file-name -s f -d 'Display the name of the containing file before each string'
complete -c strings -l radix -s t -d 'Display the offset within the file of each string, before the string and usin…'
complete -c strings -l version -d 'Display the version of the llvm-strings executable'

